package com.nanda.firstrestapi.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.nanda.firstrestapi.app.AppConstants;
import com.nanda.firstrestapi.data.model.UserModel;
import com.nanda.firstrestapi.data.repo.UserRepository;

@RestController
public class MobileApiController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping(value = AppConstants.BASE_METHOD_MOBILE + "/data")
	public String getData() {
		return "Test Data Success";
	}

	@GetMapping(value = AppConstants.BASE_METHOD_MOBILE + "/test")
	public String getTestData(@RequestParam(value = "name") String name) {
		return name;
	}

	@GetMapping(value = AppConstants.BASE_METHOD_MOBILE + "/testData")
	public String getTestData(@RequestParam(value = "name") String name, @RequestParam(value = "age") int age) {
		return name + "" + age;
	}

	@GetMapping(path = AppConstants.BASE_METHOD_MOBILE + "/all")
	public @ResponseBody List<UserModel> getAllUsers() {
		// This returns a JSON or XML with the users
		return (List<UserModel>) userRepository.findAll();
	}

}
